version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: tradie
      MYSQL_DATABASE: tradie
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  # ui:
  #   entrypoint: ["npm", "start"]
  #   environment:
  #     NODE_ENV: development
  #   image: node:10.15-alpine
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./ui:/opt/ui
  #   working_dir: /opt/ui
